spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false;
        format_sql: true;
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: ${SECURITY_SECRET}
    header: Authorization
    prefix: Bearer
    expiration: 1
    refresh:
      expiration: 7